<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Exam

# Problem 1

In [7]:
import numpy as np
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)


[[13.]
 [57.]
 [19.]]


# Problem 2

In [8]:
#To get the Eigenvalue/s and Eigenvectors "np.linalg.eig" is used
A = np.array ([[8,5,-6],[-12,9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are:",v)
#x = v.round()
#print(x)

[[  8   5  -6]
 [-12   9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [10.+9.74679434j 10.-9.74679434j  2.+0.j        ]
The right eigenvectors are: [[-6.19826768e-02-0.44653265j -6.19826768e-02+0.44653265j
   7.07106781e-01+0.j        ]
 [ 8.56977879e-01+0.j          8.56977879e-01-0.j
  -1.66861154e-16+0.j        ]
 [ 9.43214647e-03+0.24953295j  9.43214647e-03-0.24953295j
   7.07106781e-01+0.j        ]]


# Problem 3

In [44]:
#It's an error since the input A is not a Square Matrix.

A = np.array([[1,1],[2,3],[2,1]])
print(A)
B = np.array([[4],[14],[2]])
print(B)


inv_A = np.linalg.inv(A)
print(inv_A)
X = np.dot(inv_A,B)
print(X)

[[1 1]
 [2 3]
 [2 1]]
[[ 4]
 [14]
 [ 2]]


LinAlgError: ignored