<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [37]:
import numpy as np
A = np.array([[1,3],[2,7]])
print(A)
invA = (np.linalg.inv(A))
print(invA)

[[1 3]
 [2 7]]
[[ 7. -3.]
 [-2.  1.]]


In [38]:
C = np.dot(A,invA)
print (C)

[[1. 0.]
 [0. 1.]]


In [28]:
##Python Programming to Transpose a 3x3 Matrix A =([7,2,3],[5,-3,2],[3,9,6]) 
A = np.array([[7,2,3],[5,-3,2],[3,9,6]])
print(A)
B = np.transpose(A)
print(B)

[[ 7  2  3]
 [ 5 -3  2]
 [ 3  9  6]]
[[ 7  5  3]
 [ 2 -3  9]
 [ 3  2  6]]


In [40]:
##Python Programming to Inverse a 3x3 Matrix A =([7,2,3],[5,-3,2],[3,9,6]) 
A = np.array([[7,2,3],[5,-3,2],[3,9,6]])
print(A)
invA = (np.linalg.inv(A))
print(invA)

[[ 7  2  3]
 [ 5 -3  2]
 [ 3  9  6]]
[[ 0.26086957 -0.10869565 -0.0942029 ]
 [ 0.17391304 -0.23913043 -0.00724638]
 [-0.39130435  0.41304348  0.22463768]]
