<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Midterm Exam

Question 1. Create a Python code that displays a square matrix whose length is 5

In [32]:
import numpy as np
np.arange(1, 26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [18]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

Question 3. Create a Python code that displays a square matrix which is symmetrical

In [26]:
A = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(A)
print("\n")
print(np.transpose(A))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


[[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]


Question 4. What is the inverse of matrix C? Show your solution by python coding

In [48]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])

C = np.linalg.inv(C)
print('Matrix C\n',C)

Matrix C
 [[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding

In [35]:
print((np.linalg.det(C)))

print(round(np.linalg.det(C)))

5.000000000000001
5


Question 6. Find the roots of the linear equations by showing its python codes

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [44]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(A)
print("\n")
inv_A = np.linalg.inv(A)
print(inv_A)
print("\n")
B = np.array([[3.4],[8.8],[19.2]])
print(B)
print("\n")
X = np.dot(inv_A,B)
print(X)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]


[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]


[[ 3.4]
 [ 8.8]
 [19.2]]


[[0.2]
 [0.4]
 [0.8]]
