<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

a. WY

In [31]:
import numpy as np
np.dot(W,Y)

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

b. Z+Z

In [21]:
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


c. 3X

In [25]:
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(3*X)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


**Problem 2**

a. The product (YW)² is not defined

In [56]:
YW = np.dot(Y,W)
print (np.square(YW))
#The statement is False since the following equation is defined.

[[25 49]
 [16 16]]


b. WY – X =

In [34]:
A = np.dot(W,Y)
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(A-X)
#As a result, the statement is True.

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


c. YW – Z² =

In [44]:
YW = np.dot(Y,W)
print (YW- np.square(Z))
#As a result, the statement is False.

[[ 5 -8]
 [ 0 -5]]
