<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations


In [39]:
import numpy as np
#Addition of Matrices
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)


[[ 1 -3]
 [ 6  4]]


In [40]:
#Subtraction of Matrices
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)



[[-11   3]
 [  2  -2]]


In [41]:
#Subtraction of Matrices
b = np.array([[6,-3],[2,3]])
b = np.array([[6,-3],[2,3]])
print(b-b)

[[0 0]
 [0 0]]
