<a href="https://colab.research.google.com/github/amnbg/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations




In [2]:
import numpy as np
#Create a 1 x 3 matrix
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#Create a 2 x 3 matrix
b = np.array([[1,2,3],[4,5,6]]) #This is an example of rectangular
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#Create a 3 x 3 matrix
c = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Create a constant array with all values are 9
d = np.full((4,4),9) #This is an example of square matrix
print(d)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [6]:
#Create a diagonal matrix
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [7]:
#Create an identity matrix
f = np.eye(9)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
#Create a zero matrix
g = np.zeros((6,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#Create an empty matrix
h = np.empty((0,5))
print(h)

[]


In [10]:
#Addition of Matrices
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print(i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
#Subtraction of Matrices
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print(i-j)


[[ 2  0 -1]
 [-3  1  4]]
